#!/bin/bash
# Flask Installation

# Copy file to directory you want (workspace), then CD there
# -->chmod 700 framework_install
# -->./framework_install
# Remove installation file


sudo easy_install Flask

sudo pip install flask
sudo pip install flask-login
sudo pip install flask-openid
sudo pip install flask-mail
sudo pip install flask-sqlalchemy
sudo pip install sqlalchemy-migrate
sudo pip install flask-whooshalchemy
sudo pip install flask-wtf
sudo pip install flask-babel
sudo pip install guess_language
sudo pip install flipflop
sudo pip install coverage
sudo pip install rauth
sudo pip install Flask-OAuth
sudo pip install oauth
sudo pip install oauth2
sudo pip install requests
sudo pip install yolk
sudo pip install Jinja2
sudo pip install MarkupSafe
sudo pip install Werkzeug
sudo pip install argparse
sudo pip install itsdangerous